The-Shivam-garg/BigB-E-learn-Websit-e

Blog/blog.html, Course/Courses.html, about/team.html, contact/contact.html, index.html, log in/Login.html
Link Issue solved in about page, blog page, contact page , team page, course page and Home Page
Fix : #20 
@The-Shivam-garg 
Hey @The-Shivam-garg if you could increase the level as i found more bugs  in links of other pages as well
=> Solved Link Issue in All Pages

Blog/blog.html, index.html
I have done the necessary changes in the code that was required now Error 404 page is not coming.
=> [Issue {24}] When we click on the Home button in Navbar while we are on the Home Page an error 404 page comes

readme.md
ISSUE NO: 30
ISSUE : Feature: ADD a section in readme.md for showing the contributors. 
Updated the Readme.md file. Now the contributors are visible in that file.
=> [Issue:30] Feature: ADD a section in readme.md for showing the contributors . 

index.html
=> Real Time Updation #27

Courses.html, style.css
Hey Shivam dada, I have successfully implemented the search button for the different courses available using html, CSS and javascript, however the styling part got distorted a bit in the process. I hope someone else having expertise in that field can mend it well.
=> Implementation of the search button for courses

Blog/blog3.html
=> blog-page no.3 added

Course/subjects/Applied Science.html, Course/subjects/Arts_Humanity.html, Course/subjects/IT.html, Course/subjects/Maths.html, index.html
=> Create backend for join free online courses #25

index.html, teach-on-bigb/teach.html
Solves #60 
- I have made the necessary changes
I have tested it on my local machine. Kindly if you have some other testing online software ( eg: Netlify ), do it for the same.
@The-Shivam-garg
=> Teach-on-Bigb : Redirecting error 404 solved

css/responsive.css, index.html, style.css
Issue: #56 
The course popup is now responsive across various screens. I am attaching a few screenshots for your reference.
=> Course popup responsiveness

.vscode/settings.json, Blog/blog.html, Blog/blog2.html
=> solved  #34 no issue .

log in/Login.html, log in/login.js, log in/signup.js, log in/user_state.js
I am done with the login functionality
Check Out Live Preview --> http://bigb-e-learning-bijit.surge.sh/log%20in/Login.html
=> Adding Singin And Login Functionality

.vscode/settings.json, Blog/blog.html, Blog/blog2.html, index.html
#62 Resolved the CSS/HTML bugs that resulted in incorrect sidebar display.
=> Fixed the blog page sidebar issue.

Course/css/style.css, Course/style.css, contact/css/style.css
Fixes: #76 
The following changes were made:
- Cleaned up the code.
- The content that was hiding behind the navbar, both for the Contact and Courses pages is now visible. 
- The footer content was also hiding behind the navbar, I worked on that too.
Screenshots
| Before | After |
| :---: | :---: |
|![image](https://user-images.githubusercontent.com/72005584/154855918-891a57e9-bcde-42fd-9790-9bfc89b1bdec.png)|![image](https://user-images.githubusercontent.com/72005584/154855999-38dc90d6-f923-44b5-beb3-7f3b282d4ce4.png)|
|![image](https://user-images.githubusercontent.com/72005584/154856120-35b21b98-669b-4947-bf7d-b70b5665b048.png)|![image](https://user-images.githubusercontent.com/72005584/154856166-1e2e391f-2016-4e99-a4a5-396e54286798.png)| …
=> Updated responsiveness

css/main.css, index.html
closes #80
Placeholder disappears on focus.
Hover effect added on subscribe button. <br>
<br>
made entering email mandatory in order to subscribe. <br>
=> Placeholder and hover effects

index.html
Solves #81 
- Added form validation using regex
- Made use of pop-up msg instead of alert
Video :
https://drive.google.com/file/d/1_d7YVw-3BkqqIQbyWw6xz8m7i8Cc0TvA/view?usp=sharing
Kindly check @The-Shivam-garg
=> pop-up msg added

Blog/blog.html, Blog/blog2.html, Blog/blog3.html, Course/subjects/computer_courses.html, Course/subjects/gate.html, Course/subjects/jee.html, Course/subjects/quiz.html, feature-pg/features.html, index.html
_**Issue no : #88**_
--> Logo of the website has been updated & now its directing to home page by clicking on it.
--> Issue has been updated in 9 pages of html file.
Preview: https://tanya-gupta25.github.io/BigB-E-learn-Websit-e/
=> Directed logo of website to the home page

about/style.css
Fixes : #92 
Aligned the text using padding. 
Hope to solve many more issues!!
=> Fixed issue 92(Text-alignment)

Blog/css/Style.css
Solved  #95  no issue.
Demo link : https://sayan404.github.io/BigB-E-learn-Websit-e/
=> Solved  #95  no issue

css/main.css, index.html
UI UPDATED OF WHY EDUCATION SECTION
- [x ] My code follows the code style of this project.
- [x ] This PR does not contain plagiarized content.
=> Why education UI updates 

feature-pg/features.html
Solved #94 no issue
Closes #
Demo Link : https://sayan404.github.io/BigB-E-learn-Websit-e/
=> Solved #94 no issue

Course/Courses.html
=> Fixes Issue #128

readme.md
=> Correction in image rendoring and codeblocks for git commands

style.css
Updated the changes for the new courses blob that comes up as the site goes render first time
Closes BUG #146
[x] Changes the inconsistency in the radius of the blob
[x] added some spacing between the image and the text
[x] Tweaks the close button for the blob 
- [x ] My code follows the code style of this project.
- [x ] The title of my pull request is a short description of the requested changes.
BEFORE
AFTER
=> Changed for BUG #146 "Inconsistency in blob radius"

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/doc_issue.yaml, .github/ISSUE_TEMPLATE/feature_request.yml
Closes #100 
- Add Issue templates
=> docs: Added Issue templates

css/main.css
=> Fixes Issue #136

Blog/css/Style.css, css/main.css, feature-pg/features.css
Closes #159 
https://user-images.githubusercontent.com/82874704/156879664-f07b5638-83d0-4564-be34-832a2a751b11.mp4
=> Added card hover effect

css/main.css, index.html
Closes #
changed the footer color
made it responsive
on hovering over the links the text shifts a little bit towards left
and gave it a new and clean look
- [x ] My code follows the code style of this project.
- [ x] This PR does not contain plagiarized content.
old footer
new Footer
=> Footer UI updated and Conflicts resolved

Blog/blog.html, Course/Courses.html, feature-pg/features.html, index.html
Closes #149 
- Index.html
Changed wording of text and buttons.
Popup was very lengthy and hard to read, simplified it.
- Courses.html
Quote had to be credited, changed some spacing and wording errors.
- features.html
Changed navbar tabs to lowercase to be consistent with other pages.
Changed the heading to be more professional.
Fixed some typos and wording errors.
- blog.html
Changed navbar tabs to lowercase to be consistent with other pages.
Fixed some typos and wording errors.
=> Spellcheck and wording issue #149

Course/subjects/quiz.html, contact/contact.html, css/utility.css
=> Fixeed issue #172  related to Footer and Contact Us page
=> Improve Footer Text and Contact Us Fix issue #172

index.html
=> Updated index.html to link Event page

css/main.css
Description
The hover effect of last child in the what we offer section is also overflowing and can be improved!
The changes proposed were improvements in hover effect of the last element whathat we offer section.
=> issue #170 resolved - hover effect improved

index.html
Closes #
Closes #174 
- Added newsletter validation
- After a valid email is submitted, then only the student count will increase.
https://user-images.githubusercontent.com/78646418/157087518-31587fd6-7bf2-4702-a5bb-f789bfe769cd.mp4
Kindly check @The-Shivam-garg
=> Newsletter validation added

index.html, readme.md
Updation in the year of footer and readme.md file
=> issue #176 resolved - Dynamic year added in footer and readme.md file

style.css
check if  the changes are ok .
=> solved Issue#175

app.js, index.html, style.css
fixes #175 
reduced the gap in navbar and fixed the height
=> fixed space in navbar and reduced it's height

css/main.css
Issue No- #191 
Changed the Background of the JOIN FREE ONLINE COURSES section.
=> Background Updated 

css/main.css, index.html
Reverts The-Shivam-garg/BigB-E-learn-Websit-e#186
=> Revert "changes made in buttons and subscribe button"

Blog/css/Style.css, log in/style.css
=> made signin page responsive as pre issue #200 .
=> added some css in blog page.
=> you can see enhancement by below picture
=> make responsive signinpage and update blog page css issue #200

css/main.css
Closes #
Added Round Edges To "WHAT WE OFFER" SECTION.
=> Added round edges to "WHAT WE OFFER" section #204

index.html, style.css
Closes #115 
- Added Sticky Header Feature
- This feature will help user to easily move to other parts of your website without having to scroll all the way to the very top.
=> #115 Added Sticky Header Feature

index.html, style.css
Closes #116 
- Added animated underlined text on hover
=> #116 Added animated hover effect

log in/Login.html, log in/login.css, log in/login.js
Closes #202 
Changes in Login.html and login.js
Added the button which toggles the visibility of the password entered by user.
=> toggle password visibility

style.css
=> changed the color of icons in homepage

log in/Login.html, log in/login.js, log in/signup.js
Closes #210 
1.Added confirm password field in signup page.
2.Then checked if both password matches,
If they don't, then an alert is displayed. 
3.Added a button which toggles the visibility of confirm-password (from show->hide and vice versa)
=> confirm Password field added

css/main.css
Made necessary changes to fix issue #226. Please find the below screenshots.
Initially, it was something like this:
Now, it looks like this:
Please let me know if there are any more changes that need to be done. 
Thank you!  : )
=> made change in text  hover color

Blog/css/Style.css, Course/css/style.css, Course/style.css, Events/css/styles.css, Events/features.css, Resource_Page/css/resources.css, Resource_Page/css/styles.css, about/style.css, about/style1.css, contact/css/style.css, contact/css/style1.css, css/courses.css, css/main.css, css/utility.css, log in/login.css, log in/style.css, slick-1.8.1/styles.css, teach-on-bigb/teach.css
*Fixed #220 
I have added smooth scroll in the entire website.
Fixed #220
=> Added smooth scroll in website

css/main.css
Closes #230 
Made it appropriate.
=> Made it appropriate

feature-pg/feature.html
=> Updated the links for footer

css/main.css, index.html
*Fixed #221 
Fixes #221 
I have improved footer of the website by changing fonts, colors. I have applied different hover effects.
| Before | After |
| ----- | ----- |
| ![ss](https://user-images.githubusercontent.com/85051124/161695867-6e4d3eb6-b8b3-47ad-9d71-99625d8ae597.png) | ![pic1](https://user-images.githubusercontent.com/85051124/161695937-3827a212-d4d5-4ece-a650-2d750019ee56.png) |
=> Improved footer

Blog/css/Style.css, Course/css/style.css, contact/css/style.css, style.css
=> Added custom scrollbar

feature-pg/assets/css/style.css, feature-pg/assets/js/script.js, feature-pg/feature.html
Closes #247 
Added scroll to top button in feature page
=> scrollToTop button added in feature page

contact/css/style.css, css/main.css, css/utility.css, feature-pg/feature.html, index.html, style.css
I have changed the header color and UI of navbar . 
I have also included the Sign-In option in the navbar as the extra button on every page was hiding certain elements of the pages .
=> Changed the header color and UI of navbar 

.vscode/settings.json, Course/Courses.html, index.html, style.css
fixed the dark mode button position and links of explore section in course page ..
now every links are working properly in explore section of course page
DARK  MODE BUTTON position 
EXPLORE SECTION'S LINK 
NOW ,you can see that feautre link of explore section are working properly and opening....and other links are also working properly..
=> fixed dark mode buton and explore section's links

css/main.css
Closes #292 
Smoothen the hover transition in `What we offer section` in the home page to make it more responsive and give a better rate review to the UI.
=> Smoothen Hover Transition

css/main.css
Closes #293 
Added scale animation on card hover in the `homepage > WORLD-CLASS LEARNING` section
PR made under GSSoC'22 contribtions.
https://user-images.githubusercontent.com/64689436/162529292-b861bc81-64df-46e4-9c96-d59b945f5e2c.mp4
=> Added animation on card hover

Course/subjects/Art_and_Design.html, Course/subjects/Business_Strategy.html, Course/subjects/Data_Science.html, Course/subjects/Finance.html, Course/subjects/Lifestyle.html, Course/subjects/Marketing.html, feature-pg/feature.html
Closes #242 
Created html files in /course/subjects of each respective course and linked them with courses of feature page.
=> links of courses added

css/main.css
Closes #306 
Improved the hover transition in `Footer > Social Media Links` section in the home page to make it more responsive and give a better rate review to the UI.
=> Improved Footer Social Media Links Animation

index.html, style.css
Closes #307 
Refactored Navigation Bar
=> Refactored NavBar

Course/Courses.html, Course/script1.js, Course/style.css
Closes #308 
Added Scroll to top button in courses page.
=> Scroll to top button added in Courses page

index.html
=> Fixed the main content

feature-pg/feature.html
Closes #331 
Added links to the buttons in feature page
=> Added links to buttons

contact/css/style1.css
=> Removed Padding in Contact Us

feature-pg/assets/css/style.css, feature-pg/feature.html
*Fixed #342 
Fixes #342
| Before | After |
| --- | ---- |
| ![pic1](https://user-images.githubusercontent.com/85051124/165142010-25ff7f30-e5d3-4606-899d-265f643e58a5.png) | ![ss2](https://user-images.githubusercontent.com/85051124/165142042-c2d1b5d9-7df2-4157-a727-932e8d66699a.png) |
=> Added navbar in feature page

index.html, style.css
Closes #324 
Editted NavBar to make it responsive with mobile devices.
https://user-images.githubusercontent.com/64689436/165119923-f197eaeb-f39b-4d4a-95cd-70edd421c35b.mp4
=> Applying mobile responsivness on navbar

Blog/blog.html, Blog/css/Style.css, Course/Courses.html, contact/contact.html, index.html, style.css
Closes #345 
Added social link to all the pages.
=> Social links added

Course/Courses.html, css/courses.css, css/utility.css
Closes #327
Hey, as per the issue #327 I tried to improve how the 'Courses' page looked by removing redundant code and fixing some features and css. 
The page before:
The page after the changes:
Kindly review my pull request.
=> Improved the UI of 'Courses' page

feature-pg/assets/css/style.css, index.html, style.css
Closes #352 
Kindly Review the PR
=> updated the hover effect and font of navbar

Course/Courses.html, contact/contact.html
Closes #350 
Added the feature option in the side nav to directly redirect to that page.
Before:
After:
=> Added feature option in side nav

index.html
Closes #320 
Details get rendered on clicked on heading
Learn more button width increased and aligned to center.
=> rendering on clicked heading and learn more button aligned to center

css/main.css, css/responsive.css, css/utility.css
*Fixed #357 
#357 
I have improved subscribe section.
| Before | After |
| ----- | ----- |
| ![ss2](https://user-images.githubusercontent.com/85051124/166975209-b11e56d6-bc6b-46f8-9600-64bcd9ba97bf.png) | ![ss1](https://user-images.githubusercontent.com/85051124/166974838-163305c4-c3c4-411b-9cb6-8988696054e9.png) |
=> Improved subscribe section

index.html
Closes #370 
Resolved the bug in the join course.
=> Resolved the bug in join course

Course/subjects/computer_courses.html, Course/subjects/gate.html, Course/subjects/jee.html, Course/subjects/neet.html
Closes #369 
Rectified the email address in the footer for the courses
=> Updated the email address

css/main.css
Closes #365 
Scroll down to "What we offer section".
=> Converted cursor to pointer in "What we offer section"

feature-pg/assets/css/style.css, feature-pg/feature.html
Closes #359 
Updated the navbar and scroll on the feature Page.
=> Updated nav and scrollbar

style.css
Closes #377 
Button added for sign in
=> Added button for signin

Course/Courses.html, Course/css/style.css, Course/style.css
Closes #363 
Refactored Footer section in Courses page.
=> Refactored Courses Footer Section

css/main.css, index.html, style.css
=> sandhya#335

Course/subjects/Cyber Security.html, Course/subjects/Data_Science.html, Course/subjects/Finance.html, Course/subjects/Marketing.html, Course/subjects/Personal Growth.html, Course/subjects/Spirituality.html, Course/subjects/computer_courses.html, Course/subjects/gate.html, Course/subjects/jee.html, Course/subjects/neet.html
Closes #392 
Added the social links on all the course pages.
=> Added social links in all course pages

contact/contact.html, contact/css/style.css
closes #391
* Corrected animations in contact cards
* Added animation in form element
* Made cards more visible in light theme
* correctly aligned the light/dark switch button
=> Refactored Contact_Page

about/style.css, about/team.html
Closes #387 
Refactored Teams Page and added the following:
* Correctly aligned some text.
* Added decration to the text
* added animation to profile photo
* added animation to connect button
* adjusted the background color of the blog-slider so its more comfortable to the eye looking.
=> Refactored Team Page

about/style.css, css/main.css, css/responsive.css, index.html
Closes #
-Changed the UI according to the desired screenshot in PR.
=> Made changes to feedback section

Blog/blog.html, Course/Courses.html, about/team.html, community/community.html, contact/contact.html, counselling/ counselling.html, feature-pg/feature.html, log in/Login.html, navbar.css
Closes #379 
Added horizontal navbar in all pages and made separate CSS file for navbar
Please add Level3 as it took lot of effort to identify CSS code of navbar, modifying it and implementing in all pages.
GSSoC Contributor
Login Page : 
Feature page : 
Similarly uploaded in all files.
=> Added horizontal navbar in all pages

feature-pg/assets/css/style.css, style.css
*Fixed #395
#395 
I have improved the UI of navbar of home and feature section. In this I have improved hover effect of links, changed fonts, fixed margin and padding.
=> Improved Navbar of home and feature page

Course/Courses.html, teach-on-bigb/teach.html
Closes #417 
The Get started button in the teach page is now working correctly . It redirects to 'What's your domain ?" section .
=> Teach button

Course/Courses.html
Closes #415 
On clicking the get started button in courses page it goes to the courses section of same page .
=> Getstarted

feature-pg/assets/css/style.css, feature-pg/feature.html
Closes #402 
Refactored the footer on the feature page.
=> Refactored footer in feature page

index.html
Closes #
As logo in the footer is not appearing in left corner so I changed the path from dynamic logo image to a source code link made by using GitHub repo.
=> updated footer logo path

index.html
Closes #153
- Added chatbot which can answer questions related to the website.
https://user-images.githubusercontent.com/20537150/170877821-305b207d-121c-40be-8234-907acb020553.mp4
=> Added chatbot feature

Course/Courses.html, contact/contact.html, navbar.css
Closes #420 
Removed the extra space & content.
=> Fixed course and contact page

log in/Login.html, log in/login.css
=> fixed the design of login page

navbar.css
In small screen after hover, text was not changing colour until text itself get hovered. This issue was fixed now.
=> Bug fixed in hover menu in small screen

log in/Login.html
Closes #435 
- Added a `autofocus` true option for the input in sign-in 
- This results in automatically focusing the input box so that folks can get a premium experience !
- The signin and signup are a part of same file as a result autofocus is available only in signin
=> fix : Added autofocus tag

teach-on-bigb/teach.js
Slideshow effect wasn't working on teach page
Closes #441
Made the image slider on the teach page automatic
=> Added slideshow effect in teach page

.vscode/settings.json, log in/login.css, log in/style.css
Closes #436 
- Added position to eye buttons
- Removed extra margins for mobiles only
- Fixed the positions of form on mobiles
=> fix  : Signup responsiveness

css/main.css
#450 
#449 
1. Fix what we offer section in responsive
2. Refactor the testimonials section and fix its responsive issue
page still has issue from 992px to 1200px because "gain new skills" section. this section needs some work maybe I'll work on it in another PR
=> Home responsive fix

feature-pg/feature.html, feature-pg/features.css
Closes #455
Due to uneven text placement in feature section..the UI looked a bit weird so I made the changes and adjusted it.
I have made the changes in card of courses in Feature.html page
- [ x] My code follows the code style of this project.
- [ x] This PR does not contain plagiarized content.
before...
after adjusting the size
=> U.I made Even

feature-pg/feature.html
Closes #458
In specifically feature tab., The two images which I have pinned below are not correctly laid over which makes second image a bit more to be down than left one..
I have repositioned using margin CSS tag so as to make the images properly oriented
- [x ] My code follows the code style of this project.
- [ x] This PR does not contain plagiarized content.
before..
after...
================================================================================
So ,Sir please review and merge it with label Hactoberfest -accepted label otherwise it would not be counted as contribution
=> Correct the Image Position

Course/Courses.html
Closes #459
On the Courses page, adds the alt text to the graphics for each course listed for better accessibility.
=> Update Courses page with alt text

contact/contact.html
Closes #465
Fixed the bug of sign in option which was not responding in the contacts page
=> Fixed the bug of Sign in option

counselling/ counselling.html, counselling/counselling.css
Added footer section to the counselling page 
Closes #468
=> Added  footer to the counselling page

css/main.css, style.css
Closes #485 
>> Nav links given proper padding so that it looks proportional in hover state.
>>Images in Why Education section properly positioned.
=> Nav links and Images in Why Education Section fixed.

Blog/blog.html, Blog/css/Style.css
Aligned the boxes in the slider of the blog page
Closes #469
I have aligned the boxes of the slider
Before:
After:
=> Aligned boxes in blog page

feature-pg/feature.html
Closes #481 
There is uneven flow of three blog cards which needs to be smooth so as to make it a generalized attractive card.
Also in this section, the top button is somewhat clumsy and I think it should be somewhat upgraded
I have made changes to blog section as well as top button
- [ x] My code follows the code style of this project.
- [ x] This PR does not contain plagiarized content.
before..
after...
=> Changes in U.I of feature section in blog and top button

index.html
Improves page load time.
Reduces work for the browser.
Allows users with slow internet connections to view the content of your page without having to wait for the images to load.
Added lazy loading to all images in index.html file.
Lazy loading allows users with slow internet connections to view the content of your page without having to wait for the images to load.
=> added lazy loading to reduce initial load time

navbar.css
Closes #498
Nav links on hover now changes to white colour for better visibilty.
hover css applied on anchor tag in navbar.css file.
=> Nav links on hover fixed

Course/Courses.html, contact/css/style.css, css/main.css, feature-pg/feature.html, index.html, navbar.css, style.css
Closes #401 
Changed Navbar on hovering 
In the Contact section, made some changes in the view of the main section so that it can cover the background.
=> Made some changes in Navbar and Contact section

css/responsive.css, index.html, js/script3.js, style.css
=> overlay click to close modal , overlay ui changes

contact/contact.html
Closes #508 
https://user-images.githubusercontent.com/102550125/196019640-7bf8430f-7a74-4c53-8ec9-26caf3b6c4e8.png
=> BigB logo issue resolved in contact page

index.html
=> The text JOIN NOW in index.html is successfully transformed to anchor tag .. issue #512

Course/Courses.html, Course/css/style.css
The displaced theme toggle button is fixed on the course page.
Now
Before
=> Displaced theme toggle button is fixed

navbar.css, style.css, teach-on-bigb/teach.css
There was an overflow due to width 100vh
=> Overflow Fixed on teach.html

Course/Courses.html, Course/css/style.css
The intro section below the navbar is now visible clearly.
🛠️ Fixes Issue
Closes [#521 ](https://github.com/The-Shivam-garg/BigB-E-learn-Websit-e/issues/521)
=> Fix section below navbar

index.html, style.css
-  Fixes the color and alignment of icons of the footer-contact-info section.
-  Fixes the alignment of Quick links.
-  Fixes the responsiveness of the Footer.
<hr/>
<hr/>
<hr/>
=> Modified Footer Section
